# SPDX-FileCopyrightText: Â© 2023 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
